### ISSUE TITLE
Python package versions incompatible with code

### ISSUE THREAD

**Issue by impaktor** [Azure/cognitive-search-vector-pr#103]
When I run the `code/azure-search-vector-python-sample.ipynb` notebook, I get:
1. missing package tenacity (will be fixed by #91)
2. Running `pip install azure-search-documents --pre` installs v. 11.4.0b11, but results in error from the first python code cell `ImportError: cannot import name 'Vector' from 'azure.search.documents.models'`
3. according to #72, the following will help 
- `pip install azure-search-documents==11.4.0a20230509004 --index-url=https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-python/pypi/simple`, 
- but then I get:  `ImportError: cannot import name 'HnswVectorSearchAlgorithmConfiguration' from 'azure.search.documents.indexes.models'`
4. Running `pip install azure-search-documents==11.4.0b6` gives same error as in 3.

I've tried above on both Python 3.11.3, and python 3.9.16. I'm on latest master: d82faba46a920bc7448c13def0d32a0084ff354c

Any thoughts would be appreciated.

**Comment by harpalshergill** [comment]
I have the same issue mentioned above. When Running `pip install azure-search-documents --pre` I get `ImportError: cannot import name 'Vector' from 'azure.search.documents.models'`

If I try `pip install azure-search-documents==11.4.0b6` then I get `ImportError: cannot import name 'HnswVectorSearchAlgorithmConfiguration' from 'azure.search.documents.indexes.models'`

Any advice on this would be appreciated. thank you.

**Comment by tarockey** [comment]
+1 facing the same issue

**Comment by farzad528** [comment]
We released an updated pypi version that uses features from our latest REST API version, 2023-10-01-preview. Please use `11.4.0b8` unless otherwise stated in the notebooks. I will update the notebooks to the latest preview API version shortly.

**Comment by impaktor** [comment]
Thanks that new version fixed it for me as well. -> closing.
