### ISSUE TITLE
Best approach to configure a multi language search method with hybrid search

### ISSUE THREAD

**Issue by ivanvaccarics** [Azure/cognitive-search-vector-pr#108]
Hello,

I need some guidance regarding the configuration of Azure Cognitive Search for hybrid search and semanticity. Specifically, I have an index that contains texts in both Italian and English, and I would like to understand the best settings to use for the "analyzer" parameter during index creation, as well as the "query_language" and "query_speller" parameters in the "azure.search.documents" Python library.

The goal is to achieve consistent and relevant search results based on the search query. I would appreciate any advice or recommendations on how to configure these parameters effectively.

Thank you for your help!

**Comment by farzad528** [comment]
Thanks for your question. If you want to use Hybrid Search + Semantic re-ranking, my suggestion would be for your text fields in your index to use a language-agnostic analyzer like the Standard Lucene if you plan on having multiple languages within a single field. Alternatively, you can have two fields (E.g. "content_en" and "content_it") and use language analyzers like "English - Lucene" and "Italian - Lucene" respectively. I would also then of course have a vector field assuming the vector used a multilingual embedding model such as "text-embedding-ada-002". 

Today, you must still pass the `queryLanguage` parameter if you want to use Semantic re-ranking and Speller. However, we are working on removing the need for this property entirely in an upcoming release. Stay tuned!

**Comment by ivanvaccarics** [comment]
Hi @farzad528 thank a lot for your response. It is very clear and precise. I have a few more questions:

- When the release of the Azure Cognitive Search will be available?
- If i use a field with english analyzer and i put in Italian strings and I query in Italian, do you kind the search is good enough? Or you suggest to move it to a Standard Lucene? 

Thank a lot.
