### ISSUE TITLE
How to deploy to azure webapp the alpha libraries

### ISSUE THREAD

**Issue by amarmohax** [Azure/cognitive-search-vector-pr#32]
Hi, I have tried the code and it runs fine in my local windows machine with Python, connects to cognitive search and able to do vector search. Now, when I go to deploy it as an Azure webapp with python and flask, the deployment fails. I have added following in my "requirements" file. 

```
artifacts-keyring
azure-search-documents==11.4.0a20230509004
python-dotenv
```

Also created the pip.conf file as per instruction here. 

The error I get during deployment is as below.

` Collecting artifacts-keyring\n[06:23:06+0000]   Using cached artifacts_keyring-0.3.3-py2.py3-none-any.whl (6.6 MB)\nERROR: Cannot install azure-search-documents and azure-search-documents==11.4.0a20230509004 because these package versions have conflicting dependencies.\n[06:23:06+0000] \n[06:23:06+0000] The conflict is caused by:\n[06:23:06+0000]     The user requested azure-search-documents\n[06:23:06+0000]     The user requested azure-search-documents==11.4.0a20230509004\n[06:23:06+0000] \n[06:23:06+0000] To fix this you could try to:\n[06:23:06+0000] 1. loosen the range of package versions you've specified\n[06:23:06+0000] 2. remove package versions to allow pip attempt to solve the dependency conflict\n[06:23:06+0000] \nERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts\n\n
`
Appreciate any tips to get it deployed in azure webapp.

**Comment by visweshwar** [comment]
Is there a reason you have artifacts-keyring in your requirements file? I would remove it as I think it's at a higher version than what azure pulls in.

**Comment by amarmohax** [comment]
I tried again after removing the keyring, it's still showing same error. Here below is entire error. 

```
Deployment endpoint responded with status code 202
Configuring default logging for the app, if not already enabled
Zip deployment failed. {'id': '39aaf735-abe5-430c-8d72-8c44eee226b6', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2023-06-05T12:50:22.3999787Z', 'start_time': '2023-06-05T12:50:23.7982495Z', 'end_time': '2023-06-05T12:50:35.2278336Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://amarappf3.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://amarappf3.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'amarappf3', 'build_summary': {'errors': [{'Message': '[12:50:31+0000] Collecting Flask==2.0.2\n[12:50:31+0000]   Using cached Flask-2.0.2-py3-none-any.whl (95 kB)\n[12:50:31+0000] Collecting openai\n[12:50:31+0000]   Using cached openai-0.27.7-py3-none-any.whl (71 kB)\n[12:50:31+0000] Collecting azure-core\n[12:50:31+0000]   Using cached azure_core-1.27.0-py3-none-any.whl (174 kB)\n[12:50:31+0000] Collecting langchain\n[12:50:31+0000]   Using cached langchain-0.0.190-py3-none-any.whl (983 kB)\n[12:50:31+0000] Collecting pymssql\n[12:50:31+0000]   Using cached pymssql-2.2.7-cp310-cp310-manylinux_2_24_x86_64.whl (3.2 MB)\nERROR: Could not find a version that satisfies the requirement azure-search-documents==11.4.0a20230509004 (from versions: 1.0.0b2, 1.0.0b3, 1.0.0b4, 11.0.0, 11.1.0b1, 11.1.0b2, 11.1.0b3, 11.1.0b4, 11.1.0, 11.2.0b1, 11.2.0b2, 11.2.0b3, 11.2.0, 11.2.1, 11.2.2, 11.3.0b1, 11.3.0b2, 11.3.0b3, 11.3.0b4, 11.3.0b5, 11.3.0b6, 11.3.0b7, 11.3.0b8, 11.3.0, 11.4.0b1, 11.4.0b2, 11.4.0b3)\nERROR: No matching distribution found for azure-search-documents==11.4.0a20230509004\n\n[notice] A new release of pip available: 22.2.2 -> 23.1.2\n[notice] To update, run: pip install --upgrade pip ', 'Timestamp': '2023-06-05 12:50:31', 'ExitCode': '1', 'Recommendation': 'Please review your requirements.txt', 'UrlToGetMoreInformation': 'https://aka.ms/troubleshoot-python'}], 'warnings': []}}. Please run the command az webapp log deployment show -n amarappf3 -g ciosandbox

```

I think its not able to find the exact version. I have the pip.conf file in same directory as my code with following code in it. 
```
[global]
index-url=https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-python/pypi/simple/
```

**Comment by visweshwar** [comment]
Are you deploying it as  a docker container?

**Comment by amarmohax** [comment]
no, I am just doing a zip file deployment into azure webapp using command line. The command use for deployment is 
`az webapp deployment source config-zip --resource-group xxmygrpxx --name "xxmyappnamexx" --src "app.zip"`

**Comment by amarmohax** [comment]
Thanks, that allowed the deployment to go through. There are some other errors while running the app, I will investigate a bit more and ask for help if needed. Thanks a lot!

**Comment by Adityadt68** [comment]
or in Requirements.txt

you can put like following, I was facing the same issue when deploying to Azure function app: (**do make sure to add it at the end**)

--extra-index-url https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-python/pypi/simple/
azure-search-documents==11.4.0a20230509004
