### ISSUE TITLE
API version (2023-07-23-preview) is not supported on Postman Quickstart

### ISSUE THREAD

**Issue by shunishii** [Azure/cognitive-search-vector-pr#52]
In variables table at [vector-search-quickstart.md](https://github.com/Azure/cognitive-search-vector-pr/blob/main/docs/vector-search-quickstart.md#set-up-your-project), it says ```search-api-version``` is ```2023-07-23-preview```. But it does not work and really should be ```2023-07-01-preview```, shouldn't it?

**Comment by farzad528** [comment]
Hi, thanks, this was a typo and has been corrected.
