### ISSUE TITLE
Similarity search title and vector

### ISSUE THREAD

**Issue by phillebaba** [Azure/cognitive-search-vector-pr#53]
The current Python demo creates embeddings for both the title and content, but only uses the content vector for searching.

https://github.com/Azure/cognitive-search-vector-pr/blob/main/demo-python/code/azure-search-vector-python-sample.ipynb

Logically looking at the code the field `fields` it suggests that it would be possible to search multiple vectors. This however does not seem to be the case, and it returns an error if you attempt to pass a comma separated list of values. Will this be something that could be supported in the future, or does a solution exist today?

**Comment by farzad528** [comment]
Hi @phillebaba this is going to be supported in the next few weeks. Please stay tuned to this repo for updates.
