### ISSUE TITLE
What is the ongoing vector search API going to look like?

### ISSUE THREAD

**Issue by mikelam92** [Azure/cognitive-search-vector-pr#70]
I was using private preview, and during search I have to create `azure.search.documents.models.Vector` to pass that into search_client.search. 

Now i am on `azure-search-documents==11.4.0b6` installing by `pip install azure-search-documents --pre`, now according to the example I can skip the step of creating the Vector object, and instead pass in a list for the vector, and there is one `topk` argument instead of one in search_client call and one in Vector definition. 
```
# Perform vector search  
results = search_client.search(  
    search_text=None,  
    vector=generate_embeddings(query, cogSvcsEndpoint, cogSvcsApiKey),
    topk=3,
    vector_fields="imageVector",
    select=["title", "imageUrl"]  
) 
```
https://github.com/Azure/cognitive-search-vector-pr/blob/main/demo-python/code/azure-search-vector-image-python-sample.ipynb

It is all good but it is not matching what's shown in the public documentation https://learn.microsoft.com/en-us/rest/api/searchservice/preview-api/search-documents#request-body. Here in the request body there is clearly a `vectors` field and it is using the old object definition. 

```
     "vectors": [
      {
        "value": "a vector representation of the query",
        "k": an integer (number of nearest neighbors to return as top results),
        "fields": "a comma-delimited list of vector fields to use in the query"
      }
```

So, which way is it gonna be and what is the source of truth?

**Comment by farzad528** [comment]
@mikelam92 thanks for your feedback. We are still in preview and while the 2023-07-01-Preview REST API version won't have any further breaking changes, the SDK's may modify their syntax over time. You can find the most up-to-date python SDK sample here: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_vector_search.py

Additionally, all the python notebooks in this repo have been updated.

For now, we are supporting both a `vector` object and a `vectors` field but in the new API version moving forward, we plan to only support `vectors` array as part of the request body. Please use `vectors` moving forward.
