### ISSUE TITLE
Will nullable vectors be supported?

### ISSUE THREAD

**Issue by kirk-marple** [Azure/cognitive-search-vector-pr#71]
In our index document, we have sections for different entities which we fill in, and some support vector search, and some do not.

I've found that we need to still send an array of zeros for a vector field, even if we're not using it for that entity type.  Seems to waste some effort sending this over the wire, and makes our search document larger than they need to be, in this case.

It would be useful to allow these to be nullable, and handled on the server-side if Cog Search requires converting that null to an empty array or something.

Any plans for this, or is this just by-design for how Collection fields work?

**Comment by farzad528** [comment]
Hi @kirk-marple, thanks for the feedback. We'll add this to our backlog and keep you updated!

**Comment by farzad528** [comment]
Hi @kirk-marple, empty collection of vectors are now supported. However, null vectors are not supported and will throw an error.
