### ISSUE TITLE
customskill endpoint 404 error but local test the endpoint is working(without add to customskill)

### ISSUE THREAD

**Issue by viciaky** [Azure/cognitive-search-vector-pr#76]
Hi I followed demo-python/code/azure-search-vector-image-python-sample.ipynb to create a customskill:

            customSkill_endpoint = "https://{myresource}.cognitiveservices.azure.com/computervision/retrieval:vectorizeImage"
            skillset_name = f"{index_name}-skillset"  
            skill_uri = customSkill_endpoint
              
            skill = WebApiSkill(  
                uri=skill_uri,  
                inputs=[  
                    InputFieldMappingEntry(name="imageUrl", source="/document/metadata_storage_path"),  
                    InputFieldMappingEntry(name="recordId", source="/document/metadata_storage_name")  
                ],  
                outputs=[OutputFieldMappingEntry(name="vector", target_name="imageVector")],  
            )  
              
            skillset = SearchIndexerSkillset(  
                name=skillset_name,  
                description="Skillset to extract image vector",  
                skills=[skill],  
            )  
              
            client = SearchIndexerClient(service_endpoint, AzureKeyCredential(key))  
            client.create_or_update_skillset(skillset)  
            print(f' {skillset.name} created')  
            
            index_client = SearchIndexClient(
                endpoint=service_endpoint, credential=credential)
            fields = [
                SimpleField(name="id", type=SearchFieldDataType.String, key=True, sortable=True, filterable=True, facetable=True),  
                SimpleField(name="imageUrl", type=SearchFieldDataType.String, retrievable=True),  
                SearchableField(name="title", type=SearchFieldDataType.String, searchable=True, retrievable=True),  
                SearchField(  
                    name="imageVector",  
                    type=SearchFieldDataType.Collection(SearchFieldDataType.Single),  
                    searchable=True,  
                    vector_search_dimensions=1024,  
                    vector_search_configuration="my-vector-config",  
                ),  
            ]
            
            vector_search = VectorSearch(
                algorithm_configurations=[
                    VectorSearchAlgorithmConfiguration(
                        name="my-vector-config",
                        kind="hnsw",
                        hnsw_parameters={
                            "m": 4,
                            "efConstruction": 400,
                            "efSearch": 1000,
                            "metric": "cosine"
                        }
                    )
                ]
            )
            index = SearchIndex(name=index_name, fields=fields, vector_search=vector_search,)
            result = index_client.create_or_update_index(index)
            print(f' {result.name} created')

Then I go to azure search service and check my indexer, it gave me this error: 
Web Api response status: 'NotFound', Web Api response details: '{"error":{"code":"404","message": "Resource not found"}}'

but I test the endpoint in local with python code, it works fine:

            def get_image_embeddings(imageUrl):  
                cogSvcsEndpoint = "https://{my cognitive service resource}.cognitiveservices.azure.com/"
                cogSvcsApiKey = "{cogsvcsapikey}"
                url = f"{cogSvcsEndpoint}/computervision/retrieval:vectorizeImage"  
                params = {  
                    "api-version": "2023-02-01-preview"  
                }  
                headers = {  
                    "Content-Type": "application/json",  
                    "Ocp-Apim-Subscription-Key": cogSvcsApiKey  
                }  
                data = {  
                    "url": imageUrl  
                }  
                response = requests.post(url, params=params, headers=headers, json=data)  
                if response.status_code != 200:  
                    print(f"Error: {response.status_code}, {response.text}")  
                    response.raise_for_status()  
                embeddings = response.json()["vector"]  
                return embeddings  

May I know what did I do wrongly for adding the customskill to azure cognitive search?

**Comment by farzad528** [comment]
It looks like your Azure Function hasn't deployed correctly? Can you verify that you can call your deployed Function App via Postman?

**Comment by viciaky** [comment]
> It looks like your Azure Function hasn't deployed correctly? Can you verify that you can call your deployed Function App via Postman?

Hi. I managed to deploy the Function App and this time it works for me. But I noticed another error when the api processed over 300 images. it will throw error and show failed in acs indexer.

Same thing will happened if I just use normal python function like below:
 def get_image_embeddings(imageUrl):  
            cogSvcsEndpoint = "https://{my cognitive service resource}.cognitiveservices.azure.com/"
            cogSvcsApiKey = "{cogsvcsapikey}"
            url = f"{cogSvcsEndpoint}/computervision/retrieval:vectorizeImage"  
            params = {  
                "api-version": "2023-02-01-preview"  
            }  
            headers = {  
                "Content-Type": "application/json",  
                "Ocp-Apim-Subscription-Key": cogSvcsApiKey  
            }  
            data = {  
                "url": imageUrl  
            }  
            response = requests.post(url, params=params, headers=headers, json=data)  
            if response.status_code != 200:  
                print(f"Error: {response.status_code}, {response.text}")  
                response.raise_for_status()  
            embeddings = response.json()["vector"]  
            return embeddings  

 May I check what could be the potential reason for that?
 Many thanks in advance!

**Comment by farzad528** [comment]
Hi @viciaky, I may need you to submit a support ticket so we can dive into the logs on what the root cause of this error code is. Thanks!

**Comment by viciaky** [comment]
Hi @farzad528 . I submitted azure support ticket regarding to this. here is the TrackingID#2307270030002958
Let me know if this is the right support ticket you mentioned.
