### ISSUE TITLE
For Vectors - Cognitive Search or Cosmos DB

### ISSUE THREAD

**Issue by amarmohax** [Azure/cognitive-search-vector-pr#84]
Looks like vector embedding store and search is now supported in azure cosmos db for mongo.

https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/vector-search

So which one does Microsoft prefer for customers? Any idea? Seems cosmos one is in GA also.

**Comment by farzad528** [comment]
Thanks for the question. Using Vector capabilities in CosmosDB vs Azure Cognitive Search depend on the task you're trying to solve. 

Here are some features of both products and you can decide what may be a better fit for your use case:

- Azure Cognitive Search has a premium vector offering that allows you to store, index, and search vectors along with advanced capabilities like the Indexer to pull from any Azure data source such as CosmosDB API for NoSQL, Blob, ADLSv2, etc. Additionally, Azure Cognitive Search has Hybrid search capabilities and an L2 reranked as part of the Semantic search (preview) feature powered by Bing. Learn more: https://learn.microsoft.com/azure/search/vector-search-overview
- CosmosDB has a basic vector offering that allows you to store, index, and search vectors while only performing pure vector search and has support for MongoDB and PostgreSQL only. Not that your data must be in CosmosDB to use Vector search capabilities. Learn more: https://learn.microsoft.com/azure/cosmos-db/mongodb/vcore/vector-search

**Comment by amarmohax** [comment]
Thanks Farzad! Any news when the vector feature in Cognitive Search will become GA? Even the semantic feature of normal search in Cognitive Search is in preview. Do you have any visibility on when these will be production ready?

**Comment by farzad528** [comment]
We are committed to GA Vector Search capabilities ASAP. Semantic search will is targeted for GA near end of CY23.

**Comment by amarmohax** [comment]
Thanks, that's good to know. Good luck!
