### ISSUE TITLE
Finding or checking for existence of an index

### ISSUE THREAD

**Issue by securigy** [Azure/cognitive-search-vector-pr#88]
If I create index and populate it with documents/embeddings, the next time I run I need to do one of the following:
- Update existing index with additional documents, or
- Delete existing index and create a new one.
- Avoiding writing to existing index.

Therefore, how do I check if the index named MyTextIndex already exists before I do anything? Is there API?

**Comment by farzad528** [comment]
You can check in the portal to see if your index exists. Alternatively, you use the List Indexes API: https://learn.microsoft.com/rest/api/searchservice/list-indexes

**Comment by securigy** [comment]
Hmmm, at the same time when I am looking at the SearchIndexClass I see there is API GetIndexAsync that takes the Index name...
1. Isn't it more efficient that getting all the indexes?
2. What do I get back if it does not exist? (not clear from the API) does it throw RequestFailedException? or null as a return value?
