### ISSUE TITLE
VectorSearchAlgorithmConfiguration import error

### ISSUE THREAD

**Issue by sgautam666** [Azure/cognitive-search-vector-pr#89]
I am trying to use this approach to use embeddings in Azure. For this, I am using langchain framework as well.
While trying to create a vector store using AzureSearch(), I get this error: 

ImportError: cannot import name 'VectorSearchAlgorithmConfiguration' from 'azure.search.documents.indexes.models' (/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/search/documents/indexes/models/__init__.py)

Code for langchain:
```
embeddings: OpenAIEmbeddings = OpenAIEmbeddings(openai_api_key=os.getenv('OPENAI_API_KEY'),
                                                deployment=openai_embedding_deployment_name, 
                                                chunk_size=1)
vector_store: AzureSearch = AzureSearch(
    azure_search_endpoint=os.environ["AZURE_COGNITIVE_SEARCH_ENDPOINT"],
    azure_search_key=os.environ["AZURE_COGNITIVE_SEARCH_API_KEY"],
    index_name=index_name,
    embedding_function=embeddings.embed_query,
)
```
I am using 'azure-search-documents==11.4.0b8' version.
Please advise
Thank you

**Comment by farzad528** [comment]
Hiya! There was a recent update in the Python SDK. I don't believe that LangChain has been updated yet. 

Please see the below sample if you want to use the latest version:
https://github.com/Azure/cognitive-search-vector-pr/blob/main/demo-python/code/azure-search-vector-python-sample.ipynb

**Comment by sgautam666** [comment]
Thanks @farzad528
