### ISSUE TITLE
Are there any plans of a serverless tier for Azure Cognitive Search vector storage?

### ISSUE THREAD

**Issue by vman** [Azure/cognitive-search-vector-pr#90]
Currently, Azure Cognitive Search is looking prohibitively expensive for storing vector data. The basic tier ($75/month) only gives us 1 GB of vector storage. Also, unless I am mistaken, moving from one tier to next is not possible without losing/migrating your stored data?

Other vector dbs like Pinecone, Weaviate etc have a "pay as you grow" pricing model where you are charged based on the amount of data stored. Are there any plans in Azure Cognitive Search to provide similar options?

**Comment by khyewei** [comment]
We're indeed planning vector on serverless, where private preview is coming ~next month. Stay tuned. Pls reach out to me if you're interested in early testing.

**Comment by vman** [comment]
Thanks @khyewei ! That's good news. I will ping you as definitely interested in trying it out.
