### ISSUE TITLE
ReadMe and Python notebook mis-aligned on variable names

### ISSUE THREAD

**Issue by Briwalkr** [Azure/cognitive-search-vector-pr#94]
The Readme in the following dir (https://github.com/Azure/cognitive-search-vector-pr/tree/main/demo-python) indicates the .env file should contain an entry for **AZURE_SEARCH_API_KEY**=YOUR-SEARCH-SERVICE-ADMIN-KEY. However, the azure-search-vector-python-sample.ipynb notebook is looking for a variable named os.getenv("**AZURE_SEARCH_ADMIN_KEY**"). 

This may trip up a newbie if they don't know what they are looking for. I added AZURE_SEARCH_ADMIN_KEY to the .env file as I am just starting down the path of exploring this repo, and I don't know if there are any references to the AZURE_SEARCH_API_KEY environment variable.

**Comment by farzad528** [comment]
Thanks for the catch! I've updated the sample env file!
